### ISSUE TITLE
Special Azure introduction

### ISSUE THREAD

**Issue by sacdallago** [MusicConnectionMachine/MusicConnectionMachine.github.io#7]
Hello JSTeckers :grinning:

The lovely people at Microsoft, who are sponsoring us with access to the Azure cloud, are asking us to come and explain how their tools work! It's a wonderful opportunity to set up the environment for production and testing of your tools, and to get an insight of the overall Azure architecture, which you might chose to adopt for other projects in the future.

You will get the extraordinary opportunity to meet with someone who knows every corner of one of the rising tools for software development and to ask any question you have :grinning:

-----

As of now, the scheduled time is 2PM on the 23rd of *March, right after your presentations!
Let us know if you can make it by tonight (Monday 20th), we need to have at least 10 participants to make this happen :grinning:

Doodle: http://doodle.com/poll/vxwhdbisviuacakb

-----

Pinging @MusicConnectionMachine/group-1 @MusicConnectionMachine/group-2 @MusicConnectionMachine/group-3 @MusicConnectionMachine/group-4 @MusicConnectionMachine/group-5 @MusicConnectionMachine/group-6

**Comment by kordianbruck** [comment]
Obsolete.

**Comment by sacdallago** [comment]
:D
